networks:
  local-aws-net:
    external: true

services:
  terraform:
    image: hashicorp/terraform:1.6.0
    container_name: local-terraform-runner
    volumes:
      - .:/infra
    working_dir: /infra
    networks:
      - local-aws-net
    environment:
      - AWS_ACCESS_KEY_ID=mock-key
      - AWS_SECRET_ACCESS_KEY=mock-secret
      - AWS_DEFAULT_REGION=us-east-1
    entrypoint: /bin/sh -c
    command: >
      "
      echo '🏁 Step 1: Initializing local Terraform providers...';
      terraform init && \
      echo '🚀 Step 2: Deploying your six AWS services to Floci...';
      terraform apply -auto-approve
      "
